### ISSUE TITLE
Using with wacom tablet

### ISSUE THREAD

**Issue by jirilebl** [stiglers-eponym/BeamerPresenter#10]
On Ubuntu 20.04, using Wacom tablet, I cannot do anything other than draw in black using the tablet.  Using mouse, I get all the other tools, but with the tablet I only get "draw in thin black line" no matter what tool I select.

**Comment by stiglers-eponym** [comment]
By default tablet input devices are treated different than other input devices, with an own tool. This tool can be selected by clicking on the tool buttons with the tablet device. I added an option to instead use the same draw tool for all input devices. Add the following line to your config.
```
separate-tablet-tool=false
```

**Comment by jirilebl** [comment]
Works perfect.  I guess the reason why I was confused is that I am using the keyboard to change the tools.  Thanks!
