### ISSUE TITLE
Cursor or preview of pen location when drawing in presentation window

### ISSUE THREAD

**Issue by dschwilk** [stiglers-eponym/BeamerPresenter#12]
Thank you so much for this software -- it has been perfect for me as I moved classes online this fall.

I have one problem: The pen tool is invisible until I start drawing (pushing mouse button or touching pen to tablet). Is this some misconfiguration on my end or a bug?

I'm on Kubuntu 20.04 and BeamerPresenter 0.1.3-294.b0431f3 built from github

**Comment by dschwilk** [comment]
Found the toggle cursor option. Sorry I was looking in the wrong place.

**Comment by stiglers-eponym** [comment]
To summarize a workaround for everyone:
You can show the cursor by the action "show cursor" (analogous: "hide cursor" and "toggle cursor"). Buttons in the graphical interface and keyboard shortcuts can be connected to multiple actions. These actions must be separated by a comma in the configuration. This allows you to couple the "show cursor" option to every action which selects a pen or highlighter.

**Comment by dschwilk** [comment]
Thanks! This application has been a lifesaver for my org-mode -> beamer -> online lecture workflow and allowed less switching between applications for quick drawings and whiteboard use.
