### ISSUE TITLE
can't compile with poppler

### ISSUE THREAD

**Issue by zraktvor** [stiglers-eponym/BeamerPresenter#15]
Trying to compile with `INCLUDE_POPPLER` results in following error message:
```
src/preferences.cpp: In member function ‘void Preferences::setRenderer(const QString&)’:
src/preferences.cpp:511:5: error: expected primary-expression before ‘else’
  511 |     else if (new_renderer == "poppler + external")
      |     ^~~~
make: *** [Makefile:1003: preferences.o] Error 1
```

This seems to be caused by the following lines, which result in an `else else`:
https://github.com/stiglers-eponym/BeamerPresenter/blob/fd898bc496886098d08ec9554b49de6ce0b3185a/src/preferences.cpp#L491-L500

https://github.com/stiglers-eponym/BeamerPresenter/blob/fd898bc496886098d08ec9554b49de6ce0b3185a/src/preferences.cpp#L510-L518

Removing the `else` in line 511 should fix this.

**Comment by stiglers-eponym** [comment]
Thank's for pointing this out! I simplified the code and found one more problem when compiling without MuPDF, which should now also be fixed.
