### ISSUE TITLE
can't share windows via browsers

### ISSUE THREAD

**Issue by zraktvor** [stiglers-eponym/BeamerPresenter#16]
## System
Ubuntu 20.10, Qt 5.14.2

## Issue
When trying to share one of the windows from BeamerPresenter via discord, the browser didn't offer any of BeamerPresenter's windows. The windows from all other applications could be selected. This problem occurred in both Chromium and Firefox.

As a quick fix, I wrapped the top-level widgets in QMainWindows. This did solve the issue.
https://github.com/stiglers-eponym/BeamerPresenter/blob/4c23274450a0bfd308f82053a3a1db58c0f00605/src/master.cpp#L94-L96

was replaced by:
```c++
        QWidget* const widget = createWidget(obj, NULL);
        auto* const main_window = new QMainWindow();
        main_window->setWindowTitle("BeamerPresenter");
        main_window->setCentralWidget(widget);
        if (widget)
            windows.append(main_window);

```

**Comment by stiglers-eponym** [comment]
Thanks for finding and directly fixing this issue!
