### ISSUE TITLE
Three screens with notes

### ISSUE THREAD

**Issue by alfredoq** [stiglers-eponym/BeamerPresenter#17]
Godd morning. In first place thank you for this useful software.

I would like to know if it is possible to have three instances (screens) of the presentation? One for the audience, a second one for drawwing with a tablet and a third one with the notes? Obviously all of the synchronized.

Thank you very much in advance for the support

Best regards

Alfredo

**Comment by stiglers-eponym** [comment]
Hi,
That is possible. Here are two examples of configuration files, which can be used for that purpose. Use them as follows:
```sh
beamerpresenter -g /path/to/gui.json ...
```
The idea of the JSON format for the configuration file is to make it simple to play with the layout. Note that currently the size of the button widget is not calculated optimally and it may use too much space. This might be fixed soon.
In these configuration files I assumed that you want to use markdown notes, but of course you could also use a slide showing a separate PDF for the notes.

[gui.json.txt](https://github.com/stiglers-eponym/BeamerPresenter/files/6540286/gui.json.txt)
[gui2.json.txt](https://github.com/stiglers-eponym/BeamerPresenter/files/6540287/gui2.json.txt)

**Comment by alfredoq** [comment]
Hi, thank you very much for the prompt response,

I will try these two options and comment the results,

best regards
Alfredo

**Comment by alfredoq** [comment]
I am indeed trying to load two files .pdf: the first containing the presentation and the second one containing only the notes. As desired Igot three screens: the presentation one that is ok, the presenter one with huge tools and a very small area for the slide and drawing on it, and a third screen that is blank (expected notes). How can I change the Markdown option to a .pdf notes file option? 
Thank you

Alfredo

**Comment by stiglers-eponym** [comment]
[gui.json.txt](https://github.com/stiglers-eponym/BeamerPresenter/files/6541022/gui.json.txt)
[gui2.json.txt](https://github.com/stiglers-eponym/BeamerPresenter/files/6541023/gui2.json.txt)

The small slide was indeed my fault. Here the layout system is not really clever. I added a preview of the next slides there to fix this problem.

**Comment by alfredoq** [comment]
Thank you very much for this last example, after inspecting the .json code I got the ideally of constructing the different views, including the third window with the corresponding notes. 
Thank you very much again for support and the piece of software,
best regards

Alfredo
