### ISSUE TITLE
tool to clear all drawings?

### ISSUE THREAD

**Issue by alfredoq** [stiglers-eponym/BeamerPresenter#18]
Good morning,
is it possible to configure a button in the toolset to clear all the drawings in the slide?
Thanks in advance for the support,
Alfredo

**Comment by stiglers-eponym** [comment]
Such an action exists: The "clear" action will clear all drawings on the current slide. The configuration can be a bit tricky when you see multiple slides in parallel (presentation and notes file). Then you should make sure that in your GUI configuration (the .json file) the correct slide widget is marked as "master".
When using or LaTeX beamer's option "show notes on second screen" you need to specify what to clear: "clear left" or "clear right".

To configure the button you just need to add "clear" (it's really just a simple string, although buttons for tools are more complicated with the structure {"tool":"pen", ...}).

By the way: In the default configuration file this action is associated with the keyboard shortcut SHIFT+C.
