### ISSUE TITLE
Configuring keys in the .conf file

### ISSUE THREAD

**Issue by alfredoq** [stiglers-eponym/BeamerPresenter#19]
Good afternoon,
I would like to configure a pen color as a key by editing the beamerpresenter.conf file,
based on the available configurations present in the file by defaut, it is not clear to me how to define a key for example to set a pen with a particular color (lets say green). Is it possible to get an example?
thank you very much in advance
King regards
Alfredo

**Comment by stiglers-eponym** [comment]
Hi Alfredo,
All keys are defined in the form `key code = handler` in the section `[keys]` of the config file. For tools (like a pen), the configuration is provided in JSON format. An example:
```
[keys]
G = {'tool':'pen', 'color':'green', 'width':2, 'style':'solid'}
B = {'tool':'pen', 'color':'#0000ff', 'width':2.5, 'style':'dashed', 'device':['tablet pen','touch']}
```
This will configure key `G` for a green pen on all devices (except mouse move without buttons pressed or right mouse button or `tablet eraser`) and a key `B` for a dashed blue pen only on tablet and touch input devices.
Note that here strings are started by single quotation marks (`'`) or excaped double quotation marks (`\"`).

It is also possible to configure the keys using the GUI, only some rarely used (or tested) features like stroke style are not available in the GUI. As you can read in the manual, it is even possible to define an array of different tools for different devices for a single key. Like this you can set a different width for e.g. a tablet input device and the left mouse button.
