### ISSUE TITLE
AUR package - icons doesn't appear anymore (probably missing undocumented dependency)

### ISSUE THREAD

**Issue by mizhozan** [stiglers-eponym/BeamerPresenter#21]
I'm using beamerpresenter on Arch installed using [AUR](https://aur.archlinux.org/packages/beamerpresenter-git/). However, I can not see the tools icons anymore in recent update. This might be due to my system packages (undocumented dependency) as I remove some KDE plasma packages (See attached).

![missing_icons](https://user-images.githubusercontent.com/69701698/147044439-4e855438-089f-4494-a452-1b94aa094c59.png)

I've all `qt5-svg` and `qt5-multimedia` packages installed.

**Comment by stiglers-eponym** [comment]
First possible explanation: Did you install beamerpresenter with Qt 5 or Qt 6? `beamerpresenter --version` should tell you. When using Qt 6 (the default in the AUR package), you'll need qt6-svg for the icons.
(I'll add that as optional dependence to the AUR package.)

In case that doesn't solve the problem:
Do the icons exist in `/usr/share/beamerpresenter/icons/`? This directory should contain two directories called `actions` and `tools`.

**Comment by mizhozan** [comment]
Yes, I was using qt6 while having qt5-svg installed. Here is the version: `BeamerPresenter 0.2.1-578.6bdd004  mupdf=1.19.0 Qt=6.2.2`. It definitely solved the problem and it was upstream issue in AUR. 

Thanks a lot for this amazing app.
