### ISSUE TITLE
previous/next slide key bindings are ignored when focus is on the "thumbnails" tab

### ISSUE THREAD

**Issue by symphorien** [stiglers-eponym/BeamerPresenter#24]
Use case: after clicking on a specific slide in the thumbnails tab, it is impossible to pass beamer overlays with a presentation remote.

**Comment by stiglers-eponym** [comment]
I don't really understand what you mean. You want to navigate using a presentation remote (some USB-connected pointer with a few buttons, I assume)?

Usually these devices act like a keyboard sending PageUp (Prior) and PageDown (Next) keys. The actions connected to key events can be configured freely in the settings widget of beamerpresenter. But the default should already change to the next/previous overlay or page with PageUp/PageDown. If the default configuration does not work for some presentation remote, I'd be happy to fix it. But for that I'd need to know which events the presentation remote sends.

**Comment by symphorien** [comment]
My remote sends page up and page down. I configured the keybinding page up and page down to go to previous and next slides. It works correctly when the focused window is either the presentation window, or the presenter window but with the "slide tab". If the focus is on the presenter window with the "thumbnails" tab, then the events sent by the remote are ignored.

**Comment by stiglers-eponym** [comment]
Now I understand. The thumbnail view handles page up and page down in a different way (because it's a scrolling area). But I think I can overwrite that.
Thanks for reporting this!
