### ISSUE TITLE
Page up/Page Down has no effect - Ubuntu 22

### ISSUE THREAD

**Issue by shashi-prabh** [stiglers-eponym/BeamerPresenter#25]
The application remains stuck at slide 1. Pressing Page Up/Page Down/mouse click has no effect. Home and End keys work (show the first and the last slides, respectively). I am running on Ubuntu 22. I have tried installing the deb files (beamerpresenter-poppler-qt5-jammy-x86_64.deb, beamerpresenter-mupdf-qt5-jammy-x86_64.deb and beamerpresenter-mupdf-qt6-jammy-x86_64.deb) and building from source (enabling MuPdf and Poppler one at a time) so far. None of these work.

Error messages:
```
0.001 INFO unknown:0 - Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
0.023 WARNING unknown:0 - QSocketNotifier: Can only be used with threads started with QThread
```

Exporting QT_QPA_PLATFORM before running also has no effect.

Thank you.

**Comment by shashi-prabh** [comment]
`--config=none` has no effect. The config file follows.
Thank you.

```
[General]
automatic%20slide%20changes=true
cache%20pages=-1
external%20links=false
frame%20time=50
gestures=true
gui%20config=/etc/xdg/beamerpresenter/gui.json
manual=/usr/share/doc/beamerpresenter/README.html
memory=1.0486e+08

[drawing]
circle%20threshold=0.025
ellipse%20sensitivity=0.05
finalize%20drawn%20paths=false
history%20length%20hidden=20
history%20length%20visible=50
line%20sensitivity=0.005
mode=cumulative
rectangle%20angle%20tolerance=0.3
rectangle%20closing%20tolerance=0.1
snap%20angle=0.05

[keys]
Ctrl%2BA=select all
Ctrl%2BC=copy
Ctrl%2BO=open
Ctrl%2BQ=quit
Ctrl%2BS=save
Ctrl%2BShift%2BS=save as
Ctrl%2BV=paste
Ctrl%2BX=cut
Ctrl%2BY=redo left, redo right, redo
Ctrl%2BZ=undo left, undo right, undo
Delete=delete
End=last
Escape=clear selection
F11=fullscreen
Home=first
P=toggle timer
PgDown=next
PgUp=previous
Shift%2BPgDown=next skipping overlays
Shift%2BPgUp=previous skipping overlays
Space=update

[rendering]
page%20part%20threshold=2.5
renderer=mupdf
```

**Comment by stiglers-eponym** [comment]
`--config=none` has no effect, so even Home and End keys still work? That's strange.
I'll try to reproduce it using an Ubuntu VM.

**Comment by shashi-prabh** [comment]
No. With `--config=none`, Home and End keys also don't work.

**Comment by stiglers-eponym** [comment]
In a newly installed ubuntu 22.04 in a VM I cannot reproduce this issue. For both QT_QPA_PLATFORM=xcb or wayland the page up and page down keys work in beamerpresenter-poppler-qt5-jammy-x86_64.deb.

You could try to give me further information about your system to reproduce this issue, or you could try to run in debug mode to provide more information: When you build from source, you can use the cmake option `-DCMAKE_BUILD_TYPE=Debug` to enable debugging. Then you can run beamerpresenter with `--debug=key-input` to see which keys are recognized by the program.

**Comment by stiglers-eponym** [comment]
Just to make sure that I understand you correctly: On your system the page up and page down keys have abolutely no effect in beamerpresenter?

**Comment by shashi-prabh** [comment]
Yes

**Comment by shashi-prabh** [comment]
> In a newly installed ubuntu 22.04 in a VM I cannot reproduce this issue. For both QT_QPA_PLATFORM=xcb or wayland the page up and page down keys work in beamerpresenter-poppler-qt5-jammy-x86_64.deb.
> 
> You could try to give me further information about your system to reproduce this issue, or you could try to run in debug mode to provide more information: When you build from source, you can use the cmake option `-DCMAKE_BUILD_TYPE=Debug` to enable debugging. Then you can run beamerpresenter with `--debug=key-input` to see which keys are recognized by the program.

OK. Will do.

**Comment by stiglers-eponym** [comment]
OK, but still, this is a strange issue. If you find out what caused the problem or if you find any better debug output, please let me know.

**Comment by shashi-prabh** [comment]
The issue was with the laptop -- a Dell Inspiron one. On its keyboard Page UP/Down keys are activated only with Fn key pressed. Very poor judgement by Dell engineers. Never came across this before.

It might be better if you map slide changes to the Left and Right keys **also** in the default config file:

```
Right=next
Left=previous
PgDown=next
PgUp=previous
```

Thank you for your help.
