### ISSUE TITLE
Touch does not work in debian bullseye

### ISSUE THREAD

**Issue by saucec0de** [stiglers-eponym/BeamerPresenter#26]
Hi,

first of all, thank you for the awesome program!

I have downloaded and compiled BeamerPresenter, according to the documentation.
The version string of BeamerPresenter is the following:
BeamerPresenter 0.2.3 poppler=20.09.0 Qt=5.15.2

I am using debian bullseye 11.
All other applications work well with touch, e.g. I have also installed xounalpp, and it works fine, however, in BeamerPresenter, I can move the mouse, but after selecting the pen tool and pressing the stylus in the screen nothing happens.
I can delete drawn objects if I move the stylus while clicking on one of its buttons.
Here is a list of the touch devices:

$ xsetwacom --list devices
Wacom Pen and multitouch sensor Finger touch	id: 9	type: TOUCH     
Wacom Pen and multitouch sensor Pen stylus	id: 10	type: STYLUS    
Wacom Pen and multitouch sensor Pen eraser	id: 16	type: ERASER 

(BTW, I have compiled BeamerPresenter in MacOS Ventura, and the same thing happens... but that is probably another issue?)

Thank you for any help to get the pen working!

**Comment by stiglers-eponym** [comment]
Hi,

The handling of different input devices may be a bit unintuitive. I therefore want to exclude first that this is just a usage issue.

By default, when you click on a button for selecting a pen, this pen is only connected to the input device with which you clicked the button. Thus, when you push the button with your mouse, then your mouse will function as a pen. When you push the button with the stylus, your stylus should work as a pen.

It is also possible (albeit badly documented) to define a button that always selects a tool for the same device or class of devices, independent of the device used to press the button. In the configuration this is possible by adding "device":"all" to the tool definition. Attached you find a configuration file, in which the buttons are adjusted to have this behavior: [gui.json](https://github.com/stiglers-eponym/BeamerPresenter/files/11055021/gui.json.txt).

To debug this problem, it would be simplest if you could use the attached configuration file (you can use `beamerpresenter -g /path/to/gui.json`). Does the stylus have an effect now? Can you use the stylus to push buttons and does that have any effects?

**Comment by saucec0de** [comment]
Hi Valentin,

thanks you for such a quick answer.
The hint about the "device":"all" made the stylus work properly in Debian. The cursor continues to look like a mouse cursor (in Xournal++, the cursor changes when I move the pen - not sure if the same should happen for beamerpresenter, though), but now pressing the stylus on the screen makes it draw properly. So, for me, the problem with Debian is solved. (by the way, I am using Debian on a Lenovo Yoga 370).

However, I have tried also the gui.json that you give me in the MacOS, and I observe a very strange behaviour. Not sure if this issue should be closed (or renamed), but I see some issues in Ventura. The version string of BeamerPresenter that I am using in MacOS is the following:
% beamerpresenter --version
BeamerPresenter 0.2.3 mupdf=1.21.1 Qt=5.15.8

The new issue that I observe is as follows. I start the program with:
    beamerpresenter -g gui.json.txt empty.pdf

The empty.pdf file is just used for testing - it is a blank sheet.
When I select the pen in the GUI, I can now draw in MacOS with my stylus (Wacom One CTL-472) - i.e. the stylus works fine.
However, after drawing for the first time (with or without stylus), when I move the mouse, some strange drawings start to occur. I attach a picture of it, so that you can see the issue:

<img width="400" alt="Screenshot 2023-03-23 at 21 35 34" src="https://user-images.githubusercontent.com/21975209/227354695-33ca032a-b2b2-4e6c-a579-d870c010f22a.png">

Let's forget about the fact for now that the buttons are too small...
The interesting thing is that this strange beheviour only starts happening after I first select the pen tool and draw something. Before, I can move the mouse and nothing happens. However, after drawing for the first time, its like the pen is stuck in draw mode, and also shows some strange spikes.

Again thanks a lot for your time and for the awesome program :-)

**Comment by stiglers-eponym** [comment]
This seems like input events come simultaneously from the mouse and from the stylus. Currently such a situation is not handled correctly. Thus one has to make sure that only one device is used.

The following workaround might help: Replace "all+" with "tablet pen" in the GUI config file (gui.json). Then only the stylus should work.

**Comment by saucec0de** [comment]
Awesome!
Works like a magic encantation :-)

Thanks again!

**Comment by stiglers-eponym** [comment]
To help keeping an overview of tools assigned to different devices, I created a widget which can be added to the GUI configuration (gui.json) as `{"type": "tools"}`. An example can be found in config/gui-interactive.json. This also provides an alternative way of selecting tools. Maybe that helps avoiding the problem of selecting tools per device.
