### ISSUE TITLE
Segmentation faults when drawing on slides

### ISSUE THREAD

**Issue by jbrea** [stiglers-eponym/BeamerPresenter#29]
Hi. Thanks for this fantastic presenter. I use it constantly in my lectures.
Unfortunately, I get segmentation faults at random moments in time when drawing on the slides (my students got already used to it).
I think the problem is multi-touch, e.g. when my palm touches the screen while writing with the pen, or when touching the screen at two different points with my fingers (even without using the pen).
Please let me know if I can help anything with debugging this further!

**Comment by stiglers-eponym** [comment]
Thanks for pointing this out! That was a really stupid mistake. It's fixed in the mainline version now and if I find some time, I'll prepare a bug fix release.

**Comment by jbrea** [comment]
Oh, great. Thanks a lot for the quick fix! It doesn't crash anymore on my machine.

Btw. the gui-config option is just amazing! So easy to adapt to different needs and setups.
