### ISSUE TITLE
Key press switches only beamer window, not notes window

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [stiglers-eponym/BeamerPresenter#3]
I'm using the current version and since a few weeks, pressing the left/page-down key only makes the frame on presentation/beamer window switch, the note slides stays the same. This happens with and without separate notes pdf.

If I change the window configuration the "stuck" note slide updates to the correct one.

Using i3wm, X11, archlinux and today's BeamerPresenter build.
![screenshot-2019-10-05-18-09-39](https://user-images.githubusercontent.com/40799217/66258292-74616d80-e79b-11e9-9d52-c6226445557e.png)

**Comment by stiglers-eponym** [comment]
Solved: The bug occured when a slide had no transition attribute.
