### ISSUE TITLE
Could you provide the Ubuntu 24.04 deb package?

### ISSUE THREAD

**Issue by taihup** [stiglers-eponym/BeamerPresenter#30]
Hi, I am looking for the beamerpresenter-poppler-0.2.4-qt6-noble-x86_64.deb deb package commented in https://github.com/stiglers-eponym/BeamerPresenter/blob/main/INSTALL.md. However, I can't find its location. Could you upload it please?

Thanks in advance,

**Comment by stiglers-eponym** [comment]
[beamerpresenter-poppler-qt6-noble-x86_64.deb.zip](https://github.com/user-attachments/files/16717308/beamerpresenter-poppler-qt6-noble-x86_64.deb.zip)

Hi, here is the package in the current mainline version. It will also be included in the next release.

There is still a problem with touchscreen scrolling in the thumbnail overview. I hope to fix that in the next weeks.
