### ISSUE TITLE
Laser Pointer stays on screen, even when another tool is selected

### ISSUE THREAD

**Issue by BFH-ktt1** [stiglers-eponym/BeamerPresenter#32]
Dear developers,

First of all, thanks for this great work! I switched from openboard to your tool for my teaching activities, and I love it!

Today I noticed that sometimes the laser pointer stays on the slide, even I had a situation where I had two laser-pointer "spots" on the slide. It might be that this is caused by my system:
Ubuntu 24.02 LTS with the poppler version.

Probably it is something "small" :-)

Please do not hesitate to ask if you require more information.

**Comment by stiglers-eponym** [comment]
This issue arises in different situations. I only reproduced it with table hover events. For most cases this should be solved in `862f47e` (not yet in main branch). When the pointing device reaches a slide view, all previous points should now be cleared.

If the issue remains, please write which Qt version and which devices you use.
