### ISSUE TITLE
Add Zoom Feature

### ISSUE THREAD

**Issue by minnten** [stiglers-eponym/BeamerPresenter#34]
Hello, 

i am a teacher, and your software is a great help in my daily work.

One thing I am missing, is to zoom into a specific part of the document, to highlight this place for my pupils. As I normally use regular A4 sheets there is plenty of space, which is not used, so I thought of zooming in to use it properly.

Greetings 
Minnten

**Comment by stiglers-eponym** [comment]
Hi, if I understand your use case correctly, there are three possible answers to this:

1. Flexible zoom into pages (and better scrolling). Implementing this properly will be some work and should be accompanied by other changes. Maybe I will realize that at some point. But even when implemented properly, this feature will not profit from the slide cache and can be slow in some cases. (If flexible zoom is important, Xournal++ may be an alternative.)

2. Adjust a fixed zoom to fit your needs. When showing A4 pages, you may want to use a fixed zoom to the page width. In 3deffc9 (dev branch) I implemented an option allowing you to set this zoom in the GUI configuration (option `"scroll mode aspect" : number` in the `slide` widget). In this variant the slide cache is used. However, this does not allow you to change the zoom while showing the presentation. Does this help?

3. Existing workaround: You can zoom in using the magnifier. But this is not practical in many situations.

**Comment by minnten** [comment]
Hello, 

your second version would look good for me, 
but I am not able to get it working. 

I did the following steps:

1. clone the git repro locally
2. cd into the repro and change the branch to dev
3. go to packaging
4. build it with _qt_version_major=6 makepkg -p PKGBUILD_poppler
5. install it via pacman
6. add the ` "scroll mode aspect" : 1.5,` inside /etc/xdg/beamerpresenter/gui.json 
7. start beamerpresenter with `beamerpresenter test.pdf`

but nothing changed

Thanks for working on such a specific topic. 

Greetings 
Minnten

**Comment by stiglers-eponym** [comment]
Hi,

the PKGBUILD_* files do not specify the git branch, thus you used the main branch. But the changes are not merged yet. Please use this file instead:
[PKGBUILD.txt](https://github.com/user-attachments/files/17270517/PKGBUILD.txt)

Cheers
Valentin

**Comment by minnten** [comment]
Thanks, it worked, 

I will test it this week in school and give feedback

**Comment by stiglers-eponym** [comment]
The new "drag view" tool is now merged into the main branch. With this tool you can zoom and move the view (use the scroll wheel or pinch gesture on a touch screen). As mentioned earlier, this is a feature of which I have already thought for some time. I hope this helps.
