### ISSUE TITLE
Pressing left/right/up/down does nothing on macOS

### ISSUE THREAD

**Issue by sebp** [stiglers-eponym/BeamerPresenter#8]
What arrives at [ControlScreen::keyPressEvent](https://github.com/stiglers-eponym/BeamerPresenter/blob/831d41610c5dda71ffa2e1dad8a4d7e6fce38791/src/screens/controlscreen.cpp#L979) is the correct key (e.g. `Qt::Key_Left`), but with modifier `QFlags<Qt::KeyboardModifier>(KeypadModifier)`.

**Comment by stiglers-eponym** [comment]
Should be fixed in a92fc50: Completely ignore Qt::KeypadModifier because I don't know what it should be good for here and because it cannot be defined in QKeySequence::QKeySequence(const QString& key, ...) (as far as I know). This function is used to interpret key sequences from the configuration.

**Comment by sebp** [comment]
It does work now. Thanks for the quick fix!
